spring.application.name=demo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 1. Thay localhost b?ng Host và Port c?a Railway
# C?u trúc: jdbc:mysql://<MYSQLHOST>:<MYSQLPORT>/<MYSQLDATABASE>
spring.datasource.url=jdbc:mysql://ballast.proxy.rlwy.net:34531/shoppingonline

# 2. Thay username và password b?ng thông tin trên Railway
spring.datasource.username=root
spring.datasource.password=IpDTfPflyRpWBfVJZNtKNmjsQvHbwPyZ

# 3. Gi? nguyên ho?c c?p nh?t Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true