spring.application.name= dev_mini_mart
spring.datasource.url=jdbc:mysql://localhost:3306/mini_mart_dev

spring.datasource.username=root
spring.datasource.password=Mymy14022006@

# 3. Driver ?i?u khi?n (Tùy phiên b?n, th??ng Spring Boot t? nh?n di?n)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. C?u hình Hibernate/JPA (?? t? ??ng t?o b?ng ho?c c?p nh?t script)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect